version: "3.7"
services:
 # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/rdb:/data
    restart: always
    command: redis-server 
    networks:
      servers_net:
        aliases:
            - "redis"

 

networks:
  servers_net:
    name: servers_net
    driver: bridge


