version: "3.7"
services:
  # RabbitMQ
  rmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      #RABBITMQ_ERLANG_COOKIE: abcabcabcabc
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

    networks:
      servers_net:
        aliases:
            - "rabbitmq"

networks:
  servers_net:
    name: servers_net
    driver: bridge

