version: '3.7'

services:
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      servers_net:
        aliases:
            - "kibana"
    depends_on:
      - elasticsearch

networks:
  servers_net:
    driver: bridge

volumes:
  elasticsearch:
