version: "3.7"
services:
  # RabbitMQ
  rmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: abcabcabcabc
      RABBITMQ_DEFAULT_USER: hiromaily
      RABBITMQ_DEFAULT_PASS: hiropass
    networks:
      servers_net:
        aliases:
            - "rabbitmq"

networks:
  servers_net:
    name: servers_net
    driver: bridge

