version: "3.7"
services:
  zeppelin:
    image: apache/zeppelin:0.8.1
    hostname: zeppelin
    container_name: zeppelin
    expose:
      - "8080"
      - "8443"
      - "4040"
    ports:
        - "8080:8080"
        - "8443:8443"
        - "4040:4040"
    volumes:
      - ./zeppelin/datadrive:/datadrive
      - ./zeppelin/pyspark-notebooks:/zeppelin/notebook
      - ./zeppelin/zeppelin-interpreters/interpreter.json:/zeppelin/conf/interpreter.json
    networks:
      servers_net:
        aliases: 
          - "zeppelin"

networks:
  servers_net:
    name: servers_net
    driver: bridge


