version: "3.7"
services:
#Databases
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
    volumes:
    - ./postgresql:/postgresdb
    networks:
      servers_net:
        aliases:
            - "postgres"

 
networks:
  servers_net:
    name: servers_net
    driver: bridge
