version: "3.7"
services:
 # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]      
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./redis/rdb:/var/lib/redis
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    restart: always
    command: redis-server 
    networks:
      servers_net:
        aliases:
            - "redis"

 

networks:
  servers_net:
    name: servers_net
    driver: bridge







version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command:
      - sh
      - -c
      - 'exec redis-server --requirepass "$$REDIS_PASSWORD"'
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local