version: "3.7"
services:
#Adminer
  adminer:
    restart: always
    image: dockette/adminer
    container_name: adminer
    ports:
    - "9393:80"
    networks:
      servers_net:
        aliases: 
          - "adminer"

networks:
  servers_net:
    name: servers_net
    driver: bridge