version: "3.7"
services:
#Databases
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
    volumes:
    - ./postgresql:/postgresdb
    networks:
      servers_net:
        aliases:
            - "postgres"

  mysql:
    #env_file: .env
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 12345678   
    networks:
      servers_net:
        aliases:
            - "mysql"
  sql.data:
   image: mssql-linux
   container_name: mssql-linux
   build:
     context: ./mssql
     dockerfile: Dockerfile
   ports:
      - "1433:1433"    
   environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
   networks:
      servers_net:
        aliases:
            - "mssql-linux"
 
networks:
  servers_net:
    name: servers_net
    driver: bridge
